name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [workflow_dispatch]
jobs:   
  Test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: test
        run: |
          cd C:\Windows
          start notepad.exe        
  Check-Out:
    name: Check out repository code
    runs-on: self-hosted
    steps:    
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: main
  SonarQube-Scan:
    name: Execute SonarQube Scan
    runs-on: self-hosted
    needs: Check-Out
    environment:
      name: staging
      url: http://localhost:9000/dashboard?id=githubactions-demo
    steps: 
      - name: SonarQube Scan
        run: >
          C:\Sonar-Scanner\bin\sonar-scanner.bat 
          -D"sonar.projectKey=githubactions-demo" 
          -D"sonar.sources=." 
          -D"sonar.host.url=http://localhost:9000" 
          -D"sonar.java.binaries=." 
          -D"sonar.token=sqp_5b93de5d4b3df72ac75fcf5422c339c5d1305557"
  Docker-Build-Push: 
    name: Build & Push Docker Image
    runs-on: self-hosted
    needs: [SonarQube-Scan]
    environment:
      name: staging
      url: https://hub.docker.com/repository/docker/arndvorrath/githubactionsdemo/general
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: arndvorrath/githubactionsdemo:latest
  Docker-Deploy:
    name: Deploy new Docker container
    runs-on: self-hosted
    needs: [Docker-Build-Push]
    environment:
      name: staging
      url: http://localhost:49160
    steps:
      - name: Stop old Docker container
        run: docker stop $(docker ps -a -q)
      - name: Deploy new Docker container
        run: docker run -p 49160:8080 -d arndvorrath/githubactionsdemo:latest     
  Selenium-Test:
    name: Execute Selenium Cucumber tests
    runs-on: self-hosted
    needs: [Docker-Deploy] 
    steps:
      - name: Execute Selenium Cucumber test
        run: |
          cd main
          cd Selenium
          mvn verify
      - name: Show Selenium Cucumber report
        run: C:\Progra~1\Google\Chrome\Application\chrome.exe C:\actions-runner\_work\GitHubActionsDemo\GitHubActionsDemo\main\Selenium\target\cucumber-html-reports\overview-features.html
  Karate-Test:
    name: Execute Karate Cucumber tests
    runs-on: self-hosted
    needs: [Docker-Deploy] 
    steps:
      - name: Execute Karate Cucumber test
        run: |
          cd main
          cd Karate
          mvn verify
      - name: Show Karate Cucumber Report
        run: C:\Progra~1\Google\Chrome\Application\chrome.exe C:/actions-runner/_work/GitHubActionsDemo/GitHubActionsDemo/main/Karate/target/karate-reports/karate-summary.html
  Xray-Upload:
    name: Upload Report in Xray
    runs-on: self-hosted
    needs: [Selenium-Test, Karate-Test] 
    environment:
      name: staging
      url: https://proactioneu.ent.cgi.com/jira/browse/TECHRADAR-396
    steps:
      - name: Upload Report in Xray     
        run: >
          curl.exe 
          -H "Content-Type:application/json" 
          -X POST 
          -H "Authorization:Bearer NzQ3ODI1NzE4NTg3OtuwGrJJJWBd1fg2oXpcSQi9YmFg" 
          --data @C:\actions-runner\_work\GitHubActionsDemo\GitHubActionsDemo\main\Selenium\target\cucumber.json  
          "https://proactioneu.ent.cgi.com/jira/rest/raven/1.0/import/execution/cucumber"
  Mail-Send:
    name: Send a Notification email
    runs-on: self-hosted
    needs: [Xray-Upload]
    environment:
      name: staging
      url: https://mail.google.com/mail/u/0/#inbox
    steps:   
      - name: Announcerr
        uses: singhkshitij/announcerr@v2.0
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Launching my awesomeProduct version ${{ github.event.release.tag_name }}
          body: 'C:\actions-runner\_work\GitHubActionsDemo\GitHubActionsDemo\main\Selenium\target\cucumber-html-reports\overview-features.html'
          to: qammeister@gmail.com
          from: GitHub-Actions-Demo # <qammeister@gmail.com>
          content_type: text/html
          attachments: 'C:\actions-runner\_work\GitHubActionsDemo\GitHubActionsDemo\main\Selenium\target\cucumber-html-reports\overview-features.html'
